server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payments
  flyway:
    enabled: true
    schemas: payments
    create-schemas: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.suhas.common.event"
